php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - postcss.config.js
      - tailwind.config.js
      - vite.config.js
css: true
