name: CI

on: [push, pull_request]

jobs:
  laravel-tests:
    strategy:
      matrix:
        php: ['8.1', '8.2']
        experimental: [false]
        include:
          - php: '8.3'
            experimental: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: Test on PHP ${{ matrix.php }}

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - uses: actions/checkout@v3
    - name: Relax version constraints (experimental)
      run: rm composer.lock
      if: ${{ matrix.experimental }}
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Pint formatting check
      run: php vendor/bin/pint --test
    - name: Static analysis
      run: php vendor/bin/phpstan analyse --no-progress
    - name: Generate key
      run: php artisan key:generate --env=testing
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Node dependencies
      run: npm install
    - name: Build frontend code
      run: npm run build
    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --seed --env=testing
    - name: Execute tests
      run: php artisan test --without-tty --env=testing
    - uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: ${{ matrix.php }}-logs
        path: storage/logs/*.log
        if-no-files-found: ignore
        retention-days: 30
